[project]
name = "mil"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "torchmil>=1.0.0",
    "torchvision>=0.24.1",
]
